[versions]
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.10.0"
composeBom = "2024.09.00"
kotlin = "2.0.20"
agp = "8.6.0"
compose = "1.7.0"
composeCompiler = "1.5.14"
hilt = "2.52"
retrofit = "2.11.0"
okhttp = "4.12.0"
kotlinxSerialization = "1.7.3"
coroutines = "1.9.0"
room = "2.6.1"
datastore = "1.1.1"
playServicesLocation = "21.3.0"
lifecycle = "2.8.6"
activityCompose = "1.9.3"
navigationCompose = "2.8.3"
accompanistPermissions = "0.36.0"
glance = "1.1.0"
coil = "2.7.0"
appcompat = "1.7.1"
roomCompilerProcessingTesting = "2.8.4"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }

androidx-core-ktx = "androidx.core:core-ktx:1.13.1"
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
compose-ui = "androidx.compose.ui:ui:1.7.0"
compose-material3 = "androidx.compose.material3:material3:1.3.0"
compose-ui-tooling = "androidx.compose.ui:ui-tooling:1.7.0"
compose-runtime = "androidx.compose.runtime:runtime:1.7.0"
accompanist-permissions = { module="com.google.accompanist:accompanist-permissions", version.ref="accompanistPermissions" }
coil-compose = { module="io.coil-kt:coil-compose", version.ref="coil" }

hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }

retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-kotlinx = { module = "com.squareup.retrofit2:converter-kotlinx-serialization", version.ref = "retrofit" }
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref="kotlinxSerialization" }

coroutines-core = { module="org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref="coroutines" }
coroutines-android = { module="org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref="coroutines" }

room-runtime = { module="androidx.room:room-runtime", version.ref="room" }
room-ktx = { module="androidx.room:room-ktx", version.ref="room" }
room-compiler = { module="androidx.room:room-compiler", version.ref="room" }

datastore-preferences = { module="androidx.datastore:datastore-preferences", version.ref="datastore" }
play-services-location = { module="com.google.android.gms:play-services-location", version.ref="playServicesLocation" }

glance-appwidget = { module="androidx.glance:glance-appwidget", version.ref="glance" }
glance-material3 = { module="androidx.glance:glance-material3", version.ref="glance" }

hilt-navigation-compose = "androidx.hilt:hilt-navigation-compose:1.2.0"
material-icons-extended = "androidx.compose.material:material-icons-extended:1.7.0"
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }


[bundles]
compose = ["compose-ui", "compose-material3", "compose-ui-tooling", "androidx-activity-compose", "androidx-navigation-compose"]


[plugins]
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp = { id = "com.google.devtools.ksp", version = "2.0.20-1.0.25" }